// Generates conformance/hashes/catalogs.json from the TypeScript reference: the
// §10.2 component-catalog hash and the §12.2 skill-catalog hash for a set of
// catalogs chosen to stress canonical JSON (§9) — key order, declaration order,
// escaping, non-ASCII, astral-plane characters, line separators and numbers.
// Run: node scripts/gen-hashes.ts. Review the diff by hand before committing.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ComponentCatalog } from "../src/components.ts";
import { canonicalize } from "../src/protocol.ts";
import { hashSkills, summaryOf } from "../src/skills.ts";
import type { GenUiComponentDefinition, SkillSummary } from "../src/protocol.ts";

const components: Array<{ name: string; definitions: GenUiComponentDefinition[] }> = [
    { name: "one plain definition", definitions: [{ name: "order-card", template: "<h3>{{title}}</h3>" }] },
    {
        name: "declaration order and key order never matter",
        definitions: [
            { version: "2", template: "<b>{{n}}</b>", name: "zeta", props: { b: 1, a: [2, { d: true, c: null }] } },
            { name: "alpha", tag: "x-alpha", css: ":host{display:block}", template: "<i>{{#each items}}{{this}}{{/each}}</i>" },
        ],
    },
    {
        name: "markup characters and quotes are not escaped beyond JSON's own rules",
        definitions: [{ name: "markup", template: `<a href="/x?a=1&b=2" data-payload='{"k":"v"}'>Tap & go</a>\n\t<br/>` }],
    },
    {
        name: "non-ASCII: Turkish letters, currency, CJK",
        definitions: [{ name: "price", template: "<p>İade tutarı: {{amount}} ₺ — 返金</p>", props: { label: "Öde" } }],
    },
    {
        name: "astral-plane characters (emoji) stay raw, not escaped as surrogate pairs",
        definitions: [{ name: "party", template: "<p>🎉 Order shipped 📦</p>", props: { icon: "✅" } }],
    },
    {
        name: "line and paragraph separators U+2028 / U+2029 stay raw; control characters are escaped",
        definitions: [{ name: "separators", template: "a\u2028b\u2029c\u0001d\u007fe" }],
    },
    {
        name: "numbers in shortest round-trip form",
        definitions: [{ name: "numbers", template: "<x/>", props: { int: 42, neg: -7, frac: 0.1, half: 2.5, big: 9007199254740991, exp: 1e21, tiny: 1e-7 } }],
    },
];

const skills: Array<{ name: string; summaries: SkillSummary[] }> = [
    { name: "one skill without tags", summaries: [{ name: "pdf", description: "Fill, merge and read PDF forms." }] },
    {
        name: "declaration order never matters; tags keep their order",
        summaries: [
            { name: "zeta-skill", description: "Last by name.", tags: ["b", "a"] },
            { name: "brand-voice", description: "Write in the house voice." },
        ],
    },
    {
        name: "the source stamp is not part of the hash",
        summaries: [{ name: "pdf", description: "Fill, merge and read PDF forms.", source: "server" }],
    },
    { name: "empty tags are the same as no tags", summaries: [{ name: "pdf", description: "Fill, merge and read PDF forms.", tags: [] }] },
    {
        name: "non-ASCII, astral and markup characters in a description",
        summaries: [{ name: "tr-voice", description: "Türkçe yanıt ver — ₺ fiyatlar, <b>kalın</b> & 🎉 kutlama.", tags: ["dil"] }],
    },
];

const out = {
    description:
        "Catalog hashes both implementations must mint identically (PROTOCOL.md §9, §10.2, §12.2). `canonical` is the exact string that is hashed (sha256, lowercase hex): for components the definitions sorted by name; for skills the summaries' name/description/tags (never source) sorted by name. Generated by ts/packages/core/scripts/gen-hashes.ts.",
    components: components.map((c) => {
        const catalog = new ComponentCatalog(c.definitions);
        return { name: c.name, definitions: c.definitions, canonical: canonicalize(catalog.definitions), hash: catalog.hash };
    }),
    skills: skills.map((s) => {
        const canonical = canonicalize(
            s.summaries
                .map((x) => {
                    const { source: _s, ...rest } = summaryOf(x);
                    return rest;
                })
                .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0)),
        );
        return { name: s.name, summaries: s.summaries, canonical, hash: hashSkills(s.summaries) };
    }),
};

const target = join(dirname(fileURLToPath(import.meta.url)), "../../../../conformance/hashes/catalogs.json");
writeFileSync(target, JSON.stringify(out, null, 2) + "\n", "utf8");
console.log(`wrote ${target}`);
