using Mekik;

namespace Mekik.Tests;

/// <summary>
/// conformance/hashes/catalogs.json (generated by the TypeScript reference): the
/// component-catalog hash (§10.2) and the skill-catalog hash (§12.2) must be minted
/// byte-identically by both servers, or a client moving between them re-downloads
/// on every connect. Each case pins the exact canonical string as well as its
/// sha256, so a failure says whether canonicalization or hashing drifted.
/// </summary>
public class CatalogHashConformanceTests
{
    private static readonly string FixturePath = Path.Combine(AppContext.BaseDirectory, "hashes", "catalogs.json");

    private static IReadOnlyDictionary<string, object?> Fixture() =>
        (IReadOnlyDictionary<string, object?>)Json.Parse(File.ReadAllText(FixturePath))!;

    private static IEnumerable<object[]> Cases(string section) =>
        ((IEnumerable<object?>)Fixture()[section]!).Cast<IReadOnlyDictionary<string, object?>>()
            .Select(c => new object[] { (string)c["name"]! });

    private static IReadOnlyDictionary<string, object?> Case(string section, string name) =>
        ((IEnumerable<object?>)Fixture()[section]!).Cast<IReadOnlyDictionary<string, object?>>()
            .Single(c => (string)c["name"]! == name);

    public static IEnumerable<object[]> ComponentCases() => Cases("components");
    public static IEnumerable<object[]> SkillCases() => Cases("skills");

    [Theory]
    [MemberData(nameof(ComponentCases))]
    public void Component_catalog_canonical_form_and_hash_match_the_reference(string name)
    {
        var c = Case("components", name);
        var specs = ((IEnumerable<object?>)c["definitions"]!).Cast<IReadOnlyDictionary<string, object?>>()
            .Select(d => (object)new ComponentSpec
            {
                Name = (string)d["name"]!,
                Template = (string)d["template"]!,
                Css = d.GetValueOrDefault("css") as string,
                Props = d.GetValueOrDefault("props") as IReadOnlyDictionary<string, object?>,
                Version = d.GetValueOrDefault("version") as string,
                Tag = d.GetValueOrDefault("tag") as string,
            })
            .ToList();

        var catalog = new ComponentCatalog(specs);

        Assert.Equal((string)c["canonical"]!, Json.Canonicalize(catalog.Definitions.Cast<object?>().ToList()));
        Assert.Equal((string)c["hash"]!, catalog.Hash);
    }

    [Theory]
    [MemberData(nameof(SkillCases))]
    public void Skill_catalog_hash_matches_the_reference(string name)
    {
        var c = Case("skills", name);
        var summaries = ((IEnumerable<object?>)c["summaries"]!).Cast<IReadOnlyDictionary<string, object?>>()
            .Select(s => new SkillSummary
            {
                Name = (string)s["name"]!,
                Description = (string)s["description"]!,
                Tags = (s.GetValueOrDefault("tags") as IEnumerable<object?>)?.Cast<string>().ToList(),
                Source = s.GetValueOrDefault("source") as string,
            })
            .ToList();

        var canonical = Json.Canonicalize(summaries
            .OrderBy(s => s.Name, StringComparer.Ordinal)
            .Select(s => (object?)(s with { Source = null }).ToWire())
            .ToList());

        Assert.Equal((string)c["canonical"]!, canonical);
        Assert.Equal((string)c["hash"]!, Skills.Hash(summaries));

        // Tools a skill owns (SkillEntry<TTool>, §12.6) never enter the hash: the same golden
        // holds for entries carrying tools, through the source's level-1 list.
        var withTools = summaries
            .Select((s, i) => (SkillEntry)new SkillEntry<string>
            {
                Name = s.Name, Description = s.Description, Tags = s.Tags, Instructions = "…",
                Tools = [$"tool_{i}", "another"],
            })
            .ToList();
        Assert.Equal((string)c["hash"]!, Skills.Hash(withTools));
        if (withTools.Count > 0) Assert.Equal((string)c["hash"]!, Skills.Hash(SkillSources.Inline(withTools).List()));
    }
}
