<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Mekik.ServerComponents</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Mekik.Core/Mekik.Core.csproj" />
    <ProjectReference Include="../../src/Mekik.AspNetCore/Mekik.AspNetCore.csproj" />
  </ItemGroup>

</Project>
